### ISSUE TITLE
"preflihgt_one_fig.pl" script is missing

### ISSUE THREAD

**Issue by ofenerci** [bcrowell/relativity-for-poets#1]
Hello,
I am trying to compile the book. When I run,

`make figs`

I get the error, 
```
couldn't find scripts/preflight_one_fig.pl -- are you running me from home dir? at scripts/render_one_figure.pl line 71.
make: *** [Makefile:60: figs] Error 2
```
When I peek into the scripts directory, I couldn't find the script "preflight_one_fig.pl". I wonder it is possible to update the repo with the missing file. 

I also have similar problems with your other repos. I wonder those repos are up-to-date.

**Comment by bcrowell** [comment]
Fixed, thanks.
