### ISSUE TITLE
make book error

### ISSUE THREAD

**Issue by ofenerci** [bcrowell/relativity-for-poets#2]
When I run command `make book`, 
I get the error:

```
nice ionice -n7 pdflatex -interaction=nonstopmode poets >err
syntax error at -e line 1, near ") print"
Execution of -e aborted due to compilation errors.
```
I think there is a problem with a Perl command in the makefile (not knowing anything about Perl):

`DO_PDFLATEX = echo "$(DO_PDFLATEX_RAW)" ; perl -e 'if (system("$(DO_PDFLATEX_RAW)")) {$(SHOW_ERRORS)};'
`
When I remove the Perl command from the above line, the error goes away. But this time, I am caught up with a different error:

```
perl -e 'foreach $f(<ch*/*rbtex>) {$g=$f; $g=~s/\.rbtex/temp.tex/; $c="RBTEX=$f ./scripts/fruby $f >$g"; system $c}'
make[1]: Leaving directory '/home/ofenerci/Workspace/LaTeX/relativity-for-poets'
nice ionice -n7 pdflatex -interaction=nonstopmode poets >err
nice ionice -n7 pdflatex -interaction=nonstopmode poets >err
makeindex poets.idx 1>/dev/null 2>/dev/null
make: *** [Makefile:41: book] Error 1


```

**Comment by bcrowell** [comment]
Thanks, fixed.
